/* Bundles src/ into one self-contained index.html: scripts, styles and images all inlined,
   so the app opens straight from a file and can be hosted anywhere. Run with: npm run build */
import * as esbuild from 'esbuild';
import fs from 'node:fs/promises';
import path from 'node:path';

const SRC = 'src';
const OUT = 'index.html';
const MIME = {'.png': 'image/png', '.webp': 'image/webp', '.svg': 'image/svg+xml', '.jpg': 'image/jpeg'};

const bundle = async (entry, options = {}) => {
  const result = await esbuild.build({entryPoints: [path.join(SRC, entry)], bundle: true, write: false, legalComments: 'none', ...options});
  return result.outputFiles[0].text;
};

const js = await bundle('main.js', {format: 'iife'});
const css = await bundle('styles/index.css');

let html = await fs.readFile(path.join(SRC, 'index.html'), 'utf8');
const swap = (from, to) => {
  if (!html.includes(from)) throw new Error(`build: could not find ${from} in ${SRC}/index.html`);
  html = html.replace(from, () => to);
};
swap('<link rel="stylesheet" href="styles/index.css">', `<style>\n${css}</style>`);
swap('<script type="module" src="main.js"></script>\n', '');
// a classic script at the end of <body> runs once the page exists, like the module did
swap('</body>', `<script>\n${js.replace(/<\/script/gi, '<\\/script')}</script>\n</body>`);

// inline every src="assets/…" and href="assets/…" as a data URI
const assets = [...html.matchAll(/(src|href)="(assets\/[^"]+)"/g)];
for (const [whole, attr, file] of assets) {
  const data = await fs.readFile(path.join(SRC, file));
  const mime = MIME[path.extname(file)];
  if (!mime) throw new Error(`build: no MIME type for ${file}`);
  html = html.replace(whole, () => `${attr}="data:${mime};base64,${data.toString('base64')}"`);
}

html = html.replace('<!doctype html>', '<!doctype html>\n<!-- Built from src/ by build.mjs. Do not edit this file: change src/ and run `npm run build`. -->');
await fs.writeFile(OUT, html);
console.log(`built ${OUT}: ${(html.length / 1024).toFixed(0)} KB (${assets.length} assets inlined)`);
